### ISSUE TITLE
Retrofit

### ISSUE THREAD

**Issue by SethuVignesh** [SethuVignesh/AndroidTemplateCode#1]
Http Request & Response
Json Parsing
Mulitpart
Websocket

**Comment by joicepj11** [comment]
3fa06297  UserApiInterface Api Service's. 
061d9abb  NetworkModule class's, provideRetrofit()  method gives retrofit instance. 
0aca5f54  Converter Factories for data conversions.
b3626183  RetrofitDemoActivity class's,  getUsersInfo() method shows http request response. 
638b3d5 implemented retrofit multipart request in this commit

**Comment by SethuVignesh** [comment]
For websocket integration, opening a seperate issue.
